package registry

import (
	"crypto/ed25519"
	"encoding/base64"
	"encoding/hex"
	"fmt"
)

// OmniviewPublicKeyHex is the hex-encoded Ed25519 public key used to verify plugin signatures.
// Replace this placeholder with the real key generated by `registry-cli keygen`.
var OmniviewPublicKeyHex = "c84100654c6c0d42e8a86f16253a21b7f01b8e914d83ba07ce072f086a8add31"

var omniviewPublicKey ed25519.PublicKey

func init() {
	key, err := hex.DecodeString(OmniviewPublicKeyHex)
	if err != nil {
		panic(fmt.Sprintf("failed to decode embedded public key: %v", err))
	}
	omniviewPublicKey = ed25519.PublicKey(key)
}

// SetPublicKey overrides the embedded public key used for artifact verification.
// The key must be a hex-encoded Ed25519 public key (64 hex characters).
func SetPublicKey(hexKey string) error {
	key, err := hex.DecodeString(hexKey)
	if err != nil {
		return fmt.Errorf("failed to decode public key hex: %w", err)
	}
	if len(key) != ed25519.PublicKeySize {
		return fmt.Errorf("invalid public key length: got %d bytes, want %d", len(key), ed25519.PublicKeySize)
	}
	OmniviewPublicKeyHex = hexKey
	omniviewPublicKey = ed25519.PublicKey(key)
	return nil
}

// VerifyArtifactSignature verifies that the given checksum was signed by the Omniview signing key.
func VerifyArtifactSignature(checksum, signatureB64 string) error {
	if signatureB64 == "" {
		return ErrUnsignedArtifact
	}

	sig, err := base64.StdEncoding.DecodeString(signatureB64)
	if err != nil {
		return fmt.Errorf("%w: malformed base64: %v", ErrInvalidSignature, err)
	}

	if !ed25519.Verify(omniviewPublicKey, []byte(checksum), sig) {
		return ErrInvalidSignature
	}

	return nil
}
